update
upgrade

# for github
install git

# for build ruby
install ack
install imagemagick
install libyaml
install memcached
install mysql
install node
install openssl
install par
install postgresql
install readline
install readline
install sqlite
install tree
install wget
install zsh

tap phinze/homebrew-cask || true
install brew-cask

cask install iterm2
cask install chrome
cask install virtualbox

cleanup
