source ~/.dotfiles/config/local.zsh
source ~/.dotfiles/config/tab_title.zsh
source ~/.dotfiles/config/git_autocomplete.zsh
source ~/.dotfiles/config/global.sh

# Define the directories you store your projects in in
#   ~/.dotfiles/script/personal.zsh
#
# PROJECT_PARENT_DIRS+=("$HOME/Projects")

PROJECT_PARENT_DIRS=()
PROJECT_PARENT_DIRS+=("$HOME/Projects")


if [[ -f ~/.dotfiles/config/personal.zsh ]]; then
  source ~/.dotfiles/config/personal.zsh
fi

if [[ -f ~/.dotfiles/config/personal.sh ]]; then
  source ~/.dotfiles/config/personal.sh
fi

for PARENT_DIR in ${PROJECT_PARENT_DIRS[@]} ; do
  if [ -d "$PARENT_DIR" ]; then
    for PROJECT_DIR in $(/bin/ls $PARENT_DIR); do
      if [[ ! -z `which $PROJECT_DIR 2> /dev/null` ]]; then
        if [ -d "$PARENT_DIR/$PROJECT_DIR" ]; then
          alias "$PROJECT_DIR"="cd $PARENT_DIR/$PROJECT_DIR"
        fi
      fi
    done
  fi
done

export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/share/npm/bin:$PATH"
export EDITOR="nvim"

alias dot='cd ~/.dotfiles'

alias fs='bundle exec foreman start'
alias be='bundle exec'
alias bers='be rails s'
alias berk='be rake'
alias besq='be sidekiq -C config/sidekiq.yml'
alias s3='bers -p 4000'
alias s4='bers -p 4000'
alias snfr='bers -p 5000'
alias s88='bers -p 8080'

alias v='/usr/bin/vim'
alias vim='nvim'

alias hibernateon="sudo pmset -a hibernatemode 3"
alias hibernateoff="sudo pmset -a hibernatemode 0"

# alias vim='/Applications/mvim -v'
alias todo='$EDITOR ~/.todo' 
alias dc='docker-compose'
alias hark='be rake'

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export "PYTHONPATH=$PYTHONPATH:/Users/peterderuijter/Downloads/libsvm-3.21/python"


. /Users/peterderuijter/torch/install/bin/torch-activate
