# Default Theme

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'0'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_THIN}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info 0 5 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		#"ifstat 30 255" \
		#"tmux_session_info 0 5" \
		"hostname 0 11" \
		#"ifstat_sys 30 255" \
		#"lan_ip 9 233 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}" \
		#"wan_ip 2 233" \
		"vcs_branch 0 10 " \
		"vcs_compare 0 4" \
		"vcs_staged 0 2" \
		"vcs_modified 0 3" \
		"vcs_others 0 5" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"battery 0 2 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"date_day 0 15 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"date 0 12 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"time 0 13 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
	)
fi
